# Generated by Django 5.0.6 on 2025-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_roll_no', models.IntegerField(unique=True)),
                ('student_email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
